services:
  php:
    image: basemax/docker-php8.1
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
